version: '3.8'

services:
  app:
    build:
      context: node
    container_name: app    
    networks:
      - challenge-network
    volumes:
      - /usr/src/app
    ports:
      - "3000:3000"
    restart: always
    tty: true
    depends_on:
      - web
      - db

  web:
    container_name: web       
    restart: always
    build:
      context: ./nginx
    ports:
      - "8080:80"
    networks:
      - challenge-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db    
    restart: always
    tty: true
    volumes:      
      - ./sql:/docker-entrypoint-initdb.d      
    environment:
      - MYSQL_DATABASE=challengedb
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    ports:
      - "3308:3306"
    networks:
      - challenge-network    

networks:
  challenge-network:
    driver: bridge
